export const terms = 
`
Privacy Policy

Privacy Policy (https://www.termsfeed.com/live/c3d61902-ff28-445c-a85d-4bd7bac47c3c)
Last updated: August 08, 2021

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.

Interpretation and Definitions
Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions
For the purposes of this Privacy Policy:

Account means a unique account created for You to access our Service or parts of our Service.

Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.

Application means the software program provided by the Company downloaded by You on any electronic device, named Puggum

Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Les Entreprises Puggum Inc., 8342 Boulevard Perras.

Country refers to: Quebec, Canada

Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.

Personal Data is any information that relates to an identified or identifiable individual.

Service refers to the Application.

Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.

Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.

Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

Collecting and Using Your Personal Data
Types of Data Collected
Personal Data
While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

Email address

First name and last name

Address, State, Province, ZIP/Postal code, City

Usage Data

Usage Data
Usage Data is collected automatically when using the Service.

Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.

We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.

Information from Third-Party Social Media Services
The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:

Google
Facebook
Twitter
If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.

You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.

Information Collected while Using the Application
While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:

Information regarding your location

Pictures and other information from your Device's camera and photo library

We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.

You can enable or disable access to this information at any time, through Your Device settings.

Use of Your Personal Data
The Company may use Personal Data for the following purposes:

To provide and maintain our Service, including to monitor the usage of our Service.

To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.

For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.

To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.

To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.

To manage Your requests: To attend and manage Your requests to Us.

For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.

For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.

We may share Your personal information in the following situations:

With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.
With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.
With Your consent: We may disclose Your personal information for any other purpose with Your consent.
Retention of Your Personal Data
The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.

Transfer of Your Personal Data
Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.

Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.

The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.

Disclosure of Your Personal Data
Business Transactions
If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.

Law enforcement
Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

Other legal requirements
The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:

Comply with a legal obligation
Protect and defend the rights or property of the Company
Prevent or investigate possible wrongdoing in connection with the Service
Protect the personal safety of Users of the Service or the public
Protect against legal liability
Security of Your Personal Data
The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

Children's Privacy
Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.

If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.

Links to Other Websites
Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

Changes to this Privacy Policy
We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.

We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

Contact Us
If you have any questions about this Privacy Policy, You can contact us:

By email: puggummobileapp@gmail.com

By phone number: 5147968342

Terms And Conditions

(Last modified: August 4th, 2021)

Enterprises Puggum Inc. ("EPI") is a Canadian social networking company and the owner of PUGGUMTM a social networking mobile application ( “Puggum”), which allows users to post images, videos, and react to posts. It also allows users to either follow, unfollow or send messages to other users following. It allows businesses to participate in a variety of fee-based programs regarding the posting of advertisements which are surveys and the collection of data. These terms and conditions along with EPI's Privacy Policy contain important details about registration and participation in EPI’s site and the Puggum Rewards Program ("Program" and "Terms"). Please read them carefully as they are a binding agreement between you and us.

All changes to these Terms will be posted on the website or application. Please check the "last modified" date of the Terms periodically. The Program is initially launching in Canada and the United States. We reserve the right, in our sole and absolute discretion, at any time, for any reason whatsoever, and without notice, to terminate, suspend or modify the Program or the Terms at any time and without prior individual notice, which includes, without limitation, expanding the Site and the Program to other countries.

A- OVERVIEW OF THE SITE

There are two (2) ways to participate on the Site.

1. Regular User. Users can register as a regular member giving them access to vote on contests and be eligible for prizes. This also allows them to post videos and photos. They can follow and unfollow other users as well as message users that they are both following and following them. They can block other users that they don’t like the content of.

2. Business User. For a variety of fee programs, businesses can register as "Business Members", which gives businesses access to use mobile applications create advertisement and view advertisement features. They can create an advertisement for a contest and select three reactions which would be classified as winning reactions. They can then see per advertisement the number of users that reacted. They can filter this into their age and location.

All members are referred to as "Users".

B- ELIGIBILITY TO BE A VOTER MEMBER

1. You must be a resident of Canada or the United States, be at least eighteen years old and be the sole authorized account holder of a unique and valid email address, which will be associated to your account during your participation in the Program ("Eligibility Criteria").

2. You are not eligible if you are an employee of EPI, its parent, affiliates, divisions, related companies, or a member of the immediate family or household of any such employee.

C- REGISTERING AS A VOTER MEMBER

1. To register, you must complete the online registration form by providing your first and last name, unique e-mail address, which will be used to communicate with you, gender, and date of birth ("Account Information").

2. When you register as a Voter Member, you will automatically be enrolled in the Program. The Site will require you to create a username, which will be seen on the Site if you make comments on the Site, and a password for your Program account ("Account").

3. Voter Members may only register once and EPI will only accept one account per mailing address. Voter Members must create their account from a unique IP address, which must be from the same location as the registration address on the account. Accounts created using a proxy IP will not be accepted. Voter Members found opening multiple accounts and or additional Voter Members from the same household will have all accounts deleted and will forfeit any Puggum Points accumulated in those Accounts.

4. You are solely responsible for keeping your password secure. You agree to immediately notify the Site of any security breach to or unauthorized use of your Account.

5. By registering, you: (a) certify that you meet the Eligibility Criteria; (b) consent to our collection, use and disclosure of personal information as described in the Privacy Notice below; (c) have and will provide true, accurate and complete information on the registration form and when answering surveys; (d) that you have only registered for the Site once, that you have not registered on behalf of another individual or any group or entity and that you will not use or attempt to use another's Account or create a false identity; and (e) acknowledge that you have read and agree to abide and be bound by the Terms, as they may be modified from time to time, and all decisions of EPI, which shall be final and binding in all matters relating to the Program.

D- REGISTERING AS A BUSINESS MEMBER

1. To register as a Business Member, you must sign-up as a business member and provide your standard business account information.

2. By registering as a Business Member, you agree to pay any fees due under these Terms. The fees shall be charged by a method agreed upon at the time the creation of any advertisement. Fees are charged at 0.10$ per reaction and shall be subject to change at the Site's sole discretion at any time with or without notice.

3. EPI reserves the right to immediately terminate these Terms for any breach of them by you. For any other reason, these Terms may be terminated by either EPI or you upon thirty days written notice to the other party. Upon any termination of these Terms by either party, your right to use the Site shall immediately terminate. EPI will not be liable to you or any third-party for termination of these Terms, even if the Site has previously been advised of the potential harm.

4. As a Business Member, your only right with respect to any dissatisfaction with any term, policy, guideline, action or practice of the Site, content available on the Site or change thereon, or imposition of fees for use of the Site is to terminate your use of the Site by delivering notice of termination to the Site. You agree that a subscription to the Site is not a right but a privilege and that a subscription is a contractual relationship only.

5. The EPI reserves the right to accept, refuse or limit your use of the Site for any reason.

6. The EPI has the right to change technical parameters at any time without notification or explanation. YOU ACKNOWLEDGE AND AGREE THAT USE OF THE SITE IS AT YOUR OWN RISK. EPI DOES NOT WARRANT THAT THE USE OF THE SITE WILL BE UNINTERRUPTED OR ERROR FREE; EPI DOES NOT MAKE ANY WARRANTY AS TO THE ACCURACY, RELIABILITY OR CONTENT OF ANY INFORMATION OR SERVICE PROVIDED THROUGH THE SERVICE.

7. In particular, online survey results obtained through the Site are not purported to be a statistically accurate depiction, but rather the results derived from the response to surveys by Voter Members and Unregistered Users. The results of the survey do not reflect the opinion

of EPI. EPI cannot guarantee survey response rates of its Voter Members to Business Members who pay for surveying the Sites' Voter Members.

E- GRANT OF RIGHTS AND ACCEPTABLE USE POLICY

1. EPI grants to you a non-exclusive, non-transferable, limited, terminable right to use the Site for legitimate personal and business purposes.

2. You agree that you will not upload, post, or otherwise distribute or facilitate the distribution of any content that is improper to the Site, including but not limited to, content that:

a. is false, inaccurate, misleading or deceptive;

b. violates any law or regulation of Canada, the U.S. or any other country;

c. is threatening, abusive, harassing, defamatory, libelous, discriminatory, fraudulent, invasive of another's privacy or tortuous;

d. contains links to any pornographic or other offensive sites;

e. contravenes or infringes on any patent, trademark, trade secret, copyright, right of publicity, or other proprietary right of any party;

f. instigates or incites others to commit illegal activities;

g. constitutes unauthorized or unsolicited advertising, junk or bulk e-mail,

h. constitutes any form of lottery or gambling or the conducting of any contests/raffles;

i. constitutes the selling or trading of any merchandise;

j. constitutes soliciting for advertisers/sponsors;

k. promotes, solicits or participates in chain letters or marketing/pyramid schemes;

l. contains software viruses or any other computer code, files, or programs that are designed or intended to disrupt, damage, or limit the functioning of the Site, or any software, hardware, or telecommunications equipment, or to damage or obtain unauthorized access to any data or other information of any third party; or

m. impersonates the name, image, picture or likeness of any third-party person or entity not affiliated with you unless prior consent of the third-party or the third-party's legal guardian or representative has been obtained.

3. Except through the authorized sending of surveys as permitted through the Site, you will not harvest or collect information about Voter Members or use such information for the purpose of transmitting or facilitating transmission of unsolicited bulk electronic e-mail or communications.

4. The Site provides Voter Members with the ability to invite friends to become Voter Members. "Friends" are those with whom a Voter Member has a personal/professional relationship and who are eligible to become a Voter Member. Names and email addresses of invited friends will be used to send an email using the inviting friend's email address from Puggum's server notifying them about Puggum's Program. Names and email addresses of invited friends will not be retained by the EPI unless the invited friend chooses to become a Voter Member. Prior to using the Invite a Friend feature, Voter Member must have the permission to use his/her friend's email address and name. Voter Members may not use the "Invite A Friend" Form for any other use other than to invite friends to Puggum's Program, including, but without limitation, to send: (i) to strangers; (ii) multiple invitations to the same friend; (iii) unsolicited email; or (iv) "spam". The Voter Member's email and name will appear to the friends receiving the email invitation to become a Voter Member. The Voter Member will be advised only of the referred friend's user name if the referred friend becomes a Voter Member.

5. Puggum provides Voter Members with the ability to invite friends to answer surveys. "Friends" are those with whom a Voter Member has a personal/professional relationship. Names and email addresses of friends invited to take a survey will be used to send an email using the Voter Member's email address from Puggum's server notifying them about the survey request. Names and email addresses of invited friends will not be retained by Puggum unless the invited friend chooses to become a Voter Member. Prior to using the Invite a Friend to take a survey feature, Voter Member must have the permission to use

his/her friend's email address and name. Voter Members may not use the "Invite A Friend" Form for any other use other than to invite friends to take a Puggum Survey, including, but without limitation, to send: (i) to strangers; (ii) multiple invitations to the same friend; (iii) unsolicited email; or (iv) "spam". The Voter Member's email and name will appear to the friends receiving the email invitation to take a Puggum survey.

6. Puggum provides Business Members with the ability to invite Puggum Voter Members to answer surveys for the purpose of Market Research. Business Members may not use the "Contact List" Form for any other use other than to invite Puggum Members to take the Business Member's Puggum Survey, including, but without limitation, to send: (i) multiple invitations; (ii) unsolicited messages within the email; or (iii) "spam" email messages. The Business Member's email and name will appear to the Voter Members receiving the email invitation to take a Puggum survey and Voter Members will receive Puggum reward points for taking the Business Member's Survey.

7. If you violate these Terms or Puggum learns of other unlawful or harmful use of the Site by a Member, your Member's rights may be immediately terminated under these Terms, including, but not limited to, disabling your access to the Site, cancelling your Account, or taking other action deemed appropriate, including notifying the authorities and suing for damages. EPI reserves the right to delete and or suspend your Account for any reason, without liability. EPI also reserves the right at its discretion to reverse a Voter Member's rewards points for any reason, without liability and you or the Voter Member shall have no other remedies.

F- CONTENT ON THE SITE

1. EPI is not responsible for any content posted by Members, including, without limitation, surveys, polls, videos, photos, comments posted on The Site. In general, EPI does not pre-screen, monitor, or edit the content posted by Members using blogs, comment areas or other interactive services that may be available on or through the Site. However, EPI has the right at its sole discretion to remove any content at any time that, in its judgment, does not comply with the ACCEPTABLE USE POLICY or is otherwise harmful, objectionable, or inaccurate, without notice or explanation. EPI is not responsible for any failure or delay in removing such content.

2. EPI reserves the right to approve all content including user surveys before publication. In the event that EPI deems content to be unsuitable for publication, for whatever reason, EPI may, in its sole discretion, refuse to publish said content without notice or explanation. EPI also reserves the right to edit, amend and change any and all surveys and associated questions as it sees fit prior to publication without notification or explanation. Under such circumstances you will still receive rewards points associated with posting the survey and your user name will be associated with the survey.

3. Frequency of posts: Voter members are limited to a maximum of two (2) survey submissions per week, which may or may not be published. Any additional surveys submitted will not be published. Puggum reserves the right to change the limit of the number of surveys allowed to be submitted at any time.

4. Legacy: Surveys submitted by voter members will initially be available for voting for a period at the discretion of EPI.

G- HOW VOTER MEMBERS CAN EARN REWARD POINTS

1. Rewards can be earned by: Winning a Contest at the end of the time period of the contest.

2. Puggum has the right to reverse Puggum Points earned in the event of system error.

3. Puggum reserves the right to change Puggum money eligible to be earned on various activities, to change Puggum Point redemption schemes and to terminate the Program altogether, at any time, at its sole discretion, with or without notice and without liability.

H- PUGGUM POINTS

1. Puggum Points do not represent cash. They may be redeemed pursuant to the Terms.

2. Any unused Puggum Points remaining in your Account after the end of the Program or upon termination of the Program may be automatically deleted.

3. Puggum Points are a non-negotiable credit for Rewards; they may not be brokered, bartered, attached, pledged, gifted, inherited or sold; they are not transferable to any other Account holder or other person; and they are not divisible on divorce.

4. Puggum will not be liable or responsible in any manner for any tax consequences which may flow from your participation in the Program.

I- ACCOUNT STATUS

1. Once Puggum Points have been posted, you can check your Account history and Puggum Points balance by clicking on your "Balance" tab in your account profile.

2. Your Account will be deemed correct unless otherwise challenged with evidence that, in our sole and absolute discretion, demonstrates a discrepancy that warrants correction. You must bring account discrepancies to our attention within 5 days of the event by emailing support@Puggum.ca. After the 5 days, you are deemed to have waived all claims for adjustment. We will not be liable for discrepancies, omissions, inconsistencies or errors in your Account or your collection and/or redemption of Puggum Points. We reserve the right to restrict redemption or put a "hold" on Puggum Points until an alleged discrepancy is resolved.

3. Voter Members must advise us immediately of any changes to their Additional Personal Information (as defined below in Privacy Notice) including name, address, telephone numbers and email address by emailing us at support@puggum.ca.

4. If your Account is inactive, meaning you have not done any activity eligible for earning Puggum Points for a period of twelve consecutive months, Puggum reserves the right to suspend and/or cancel your Account, without notice, and such suspension or cancellation will automatically delete all Puggum Points accumulated but not redeemed.

5. If your fail to participate reasonably in third party surveys, available via email or on your account page https://www.puggum.ca/account/index (ie "High Point Surveys" or Available Surveys found under the "Profile" area on the left of your screen, https://www.puggum.ca/account/availableSurveys ) Puggum reserves the right to limit fun surveys created by Puggum and our Voter Members, as well as to suspend and/or cancel your Account, without notice, and such suspension or cancellation will automatically delete all Puggum Points accumulated but not redeemed.

6. Puggum reserves the right to restrict redemption or put a "hold" on Puggum Points for up to thirty days from the date the Puggum Points are posted to an Account.

J- REDEEMING PUGGUM POINTS

1. Puggum Points are redeemable only for the goods and merchandise with a pre-determined Puggum Points value posted at www.puggum.ca/products/product_rewards ("Rewards"). The list of Rewards is updated on a periodic basis. EPI, in its sole and absolute discretion, may add or exclude the selection of Rewards available for redemption at any time, or adjust the Puggum points required to redeem a reward with or without notice.

2. Puggum Points are not redeemable for cash.

3. Puggum Points are only available for redemption by Voter Members in Canada and the United States.European countries that accept western union and do not have any legalities against countries can also participate. Business Members are not eligible to collect or redeem reward points.

4. It is the Voter Members responsibility to pay any taxes required by Federal, Provincial and or State legislation on Redeemed Merchandise.

5. If you wish to redeem Puggum Points towards a purchase, you must redeem all Puggum Points in your Account up to the total value of the selected item(s). If you have an insufficient amount of Puggum Points, it is not possible to pay the difference.

6. You can only redeem Puggum Points that have been posted to your Account.

7. You can only redeem Puggum Points if you have provided accurate Shipping and Additional Personal Information.

8. Redeemed merchandise may be subject to taxes, shipping charges, customs and duties, all of which are payable by the Voter Member.

9. Redeemed merchandise will shipped through reputable agencies. Puggum accepts no responsibility once the order has been shipped including for lost, late or undelivered goods. Puggum will attempt to rectify any non-delivery issues with the shipper. Any instances of goods damaged in transit will be the responsibility of the recipient to reconcile with the shipper.

10. All products available for redemption have limited stock. EPI cannot guarantee that product redeemed through the Program will be exactly as shown on the Site, although every attempt will be made to match items as closely as possible. Puggum cannot be held responsible for items being out of stock, no longer available or different from items shown.

11. Puggum is not liable for any malfunction or failure of any product to perform as expected. Standard manufacture warranties or terms and conditions as supplied by the product supplier apply. Any recourse would lie between you and the product supplier. The disclaimer under Limitation of Liability below in no way disclaims any warranties provided by the manufacturer or owner of a product available for reward point redemption displayed on the Site. EPI and the product suppliers make no representations or warranties with respect to the availability of any warranties for products used by Voter Members outside Canada and the United States.

K- VOTER MEMBERS' CONDUCT

1. We reserve the right to suspend and/or cancel your Account, permanently expel you from the Program and/or put a "hold" on, not credit, revoke and/or delete Puggum Points from your Account if we determine, in our sole and absolute discretion, that you: (a) abused the Program's privileges; (b) you do not meet the Eligibility Criteria set forth in the Terms; (c) failed to follow the Terms; (d) made a misrepresentation, including without limitation, submitting false or fictitious Personal Information; (e) redeemed merchandise that will be used for resale or commercial use, and/or (f) obtained Puggum Points as a result of any fraudulent, dishonest, misleading or illegal act, including random clicking or used a system (including online systems, communication systems, servers, computers, software or other automated means), or were otherwise improperly credited Puggum Points.

L- MAINTAINING THE SECURITY OF YOUR ACCOUNT

1. Identification may be required to confirm your Voter Membership when redeeming rewards.

2. Identification may be required to confirm the legitimacy of the account holder

3. You must notify us immediately if your password is lost or stolen and we will deactivate your Account. Upon presentation of proper identification (government issued photo ID may be required), in our sole and absolute discretion, we may reactivate your Account. We are not responsible for any redemption made using a lost or stolen password.

M- TERM AND TERMINATION

1. The term of these Terms begins upon first use or registration of the Site. The term ends when your Account is deleted or suspended either on the initiative of The Site you.

2. In the event of any dispute regarding any matter relating to use of the Site, i.e. the posting of online surveys, posting of blog content, Voter Member account balance, eligibility for points or any other related matter, the decision of EPI shall be final and binding.

N- RELEASE OF LIABILITY

1. By participating in the Program, you agree to release EPI, and all of our and their respective officers, directors, owners and employees, (collectively "Releasees") from any and all liability arising from or connected to the Program, including, without limitation, the collection, redemption or revocation or deletion of Puggum Points, the suspension, termination or modification of your Account, Terms or the Program, or for any failures, human or otherwise, or any other circumstances affecting the Program in any manner including without limitation, your ability to participate in the Program or to collect or redeem Puggum Points, your use of and participation in the Site, your use of any products or other materials obtained from the Site, the impact of any question/survey answered, posted or distribution through the Site. Efforts have been made to ensure that the information herein and related Program materials are correct. We and the other Releasees are not responsible for any errors or omissions herein or in the Program materials.

O- LIMITATION OF LIABILITY

1. TO THE EXTENT PERMITTED BY LAW, ALL ASPECTS OF THE PROGRAM AND EVERYTHING ON THE SITE IS PROVIDED "AS IS" WITHOUT ANY CONDITION, REPRESENTATION OR WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. NO ORAL ADVICE OR WRITTEN INFORMATION GIVEN BY THE SITE'S OWNERS, ITS EMPLOYEES, AGENTS OR REPRESENTATIVES OR SIMILAR CREATE A WARRANTY.

2. WITHOUT LIMITING THE FOREGOING, UNDER NO CIRCUMSTANCES, INCLUDING NEGLIGENCE, SHALL PUGGUM OR ANYONE ELSE INVOLVED IN THE SITE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OR INABILITY TO USE THE SITE, ITS CONTENTS OR ANY PRODUCTS THAT HAVE BEEN REDEEMED THROUGH THE SITE OR THAT RESULT FROM DEFECTS, MISTAKES, OMISSIONS, INTERRUPTIONS, DELAYS IN OPERATION OR TRANSMISSION, VIRUSES, DELETION OF FILES, OR FOR ANY LOSS OF PRIVACY OR CONFIDENTIALITY, HOWSOEVER CAUSED.

3. IN NO EVENT SHALL THE TOTAL LIABILITY OF EPI, OR ITS EMPLOYEES, OFFICERS, DIRECTORS, AND OWNERS FOR ANY DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EITHER JOINTLY OR SEVERALLY, EXCEED THE AGGREGATE AMOUNT OF ANY FEES PAID BY YOU FOR THE SITE.

4. The foregoing provisions are for the benefit of the Releasees, and each shall have the right to assert and enforce the provisions directly on its own behalf.

P- DISPUTES

1. By participating in this Program, you agree that: (i) you will contact us directly and give us the opportunity to try to resolve any and all disputes before you take any action in court, or otherwise; (ii) any and all disputes, claims and causes of action arising out of or connected with the Program shall be resolved individually, without resort to any form of class action; (iii) any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, but in no event legal fees; and (iv) under no circumstances will Member be

permitted to obtain awards for, and Member hereby waives all rights to claim punitive, incidental and consequential damages and any other damages other than for actual out-of-pocket expenses, and any and all rights to have damages multiplied or otherwise increased.

Q- GENERAL

1. The Program and/or any money program are void where prohibited by law.

2. Any waiver by us of the strict observance, performance or compliance with the Terms, either expressly granted or by course of conduct, shall be effective only in the specific instance and shall not be deemed to be a waiver of any of our rights or remedies as a result of any other failure to observe, perform or comply with the Terms. No delay or omission by us in exercising any of our rights or remedies shall operate as waiver thereof or of any other right or remedy.

3. If any part of the Terms is declared invalid or unenforceable by a court of competent jurisdiction, the balance of the Terms shall remain valid.

4. The Parties agree that these Terms constitute entire agreement between them regarding the Site and the Program. Any representation, warranty or condition, written or otherwise, not expressly contained in these Terms shall not be enforceable by either Party.

5. Each of the Parties acknowledges and agrees that it has not been induced to enter into these Terms by any representations not specifically stated herein.

R- CHOICE OF LAW AND JURISDICTION

1. All issues concerning interpretation and enforceability of the Terms and any and all disputes, claims and causes of action arising out of or connected with this Program or the Site shall be governed by, and construed in accordance with laws of the Province of Quebec, Canada.

S- INTELLECTUAL PROPERTY

1. You understand and acknowledge that the names, logos and other intellectual property displayed on or associated with the Site are the trademarks, and trade names of EPI and all rights associated therewith are strictly reserved. You have no rights to such trademarks or names, or to any other terms, graphics, text, concepts or methodologies, by using the Site and the material contained therein.

2. You understand that unless permitted in the Terms, you have no right to modify, translate, edit, reproduce, prepare derivative works, reverse engineer, decompile, disassemble, alter, or enhance the Site's intellectual property, including any software available on the Site.

T- PRIVACY NOTICE 1. EPI values and respects your privacy. This Privacy Notice and our Privacy Policy describe our privacy practices in relation to the Site and the Program.

2. We collect personal information, namely, Account Information, from you at registration. We use your Account Information to administer the Program, including to manage your Account, to process your redemptions, to conduct research and analysis, and as otherwise described herein and in our Privacy Policy. We also use your Account Information to send you emails related to the Program that are both administrative, for example, emails about your Account ("Program Emails"). We also use your Account Information to send you promotional emails about the products and services available as part of the Program and surveys from our Business Members ("Surveys and Promotional Emails"). We do not disclose your Account Information to Business Members. Rather, we send the Promotional Emails on their behalf. We also may allow authorized third party service providers access to all personal information

to perform services on our behalf. Our service providers are required to provide appropriate protection for all personal information and to limit their use of such information to providing services on our behalf. By providing your Account Information to us, you consent to us using the information for the specified purposes.

3. Unregistered visitors to the Site will be able to see the Voter Member's User Name or Business Member's name associated with any surveys or comments to blogs that are posted on the Site.

4. Voter Members within the Site will be able to see other Member's country along with state/province if the Voter Member has provided the Site with this information. Voter Members may email each other through the Site's internal email system.

5. Voter Members may ask other Voter Members to become "friends" within the Site. It is your decision to accept or decline any friend request. If you accept a friend request the Voter Member will also know your name, along with the State/Province and country if you have set your privacy settings to allow your friends to see individually, your country, your name and your state/province.

6. We collect your Contact and Shipping Information for the purpose of sending you merchandise that you redeem with your Puggum Points. This information may also be used by EPI to send you targeted surveys on the Puggum software or on third party software.

7. At any time after registration, you are presented with the option of providing us with more detailed personal information "Additional Personal Information". You can earn Puggum Points by providing us with Additional Personal Information. To redeem Puggum Points, you are required to complete the Additional Personal Information. If you provide Additional Personal Information, it will be used to send you more personalized and or targeted Promotional Emails or Surveys on the Puggum software or on third party software. For example, our Business Members may ask us to send surveys on their behalf to individuals within a certain salary range.

8. By agreeing to become a Voter Member, you agree to receive invitations to participate in surveys. You may unsubscribe at any time, see “How do I opt-out of information" in our Privacy Policy.

9. Making Choices. Any Voter Member who does not wish to receive Program Emails or Surveys or Promotional Emails from us or our Business Members can opt out of receiving such emails or mail by following the instructions in each such email or by emailing us at support@puggum.ca at any time. It may take up to ten (10) days to process a request received by email. 10. You can also contact our Privacy Office by emailing support@puggum.ca to change or update your Additional Personal Information, Account Information, or Contact and Shipping Information or for more information about our use of your personal information.

11. Google Analytics. Our website uses Google Analytics, a web analytics tool provided by Google, Inc. ("Google") that helps EPI us understand how visitors engage with our website and application. Google Analytics uses cookies and IP addresses. The information generated by cookies about the use of our website and your IP address will be transmitted and stored by Google on servers in the United States. Google will use this information to evaluate how visitors use our website, compile reports on website activity for us and provide other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. Google Analytics collects information anonymously, and will not associate your IP address with any other data held by Google. To opt-out of Google Analytics, you can install Google Analytics Opt-out Browser Add-On. For information about and to install Google Analytics Opt-out Browser Add-on, click here: http://tools.google.ca/dlpage/gaoptout?hl=en For more information related to Google Analytics, click here: http://www.google.ca/intl/en/analytics/privacyoverview.html 12. Our Privacy Office can be reached by email at support@puggum.ca

© 2021 Entreprises Puggum Inc., All rights reserved.



© 2021 Entreprises Puggum Inc.
Q. How secure is the application?
A. The application uses encryption for both your passwords and data being sent out. We couldn't even see your passwords if we wanted to.
Q. How will my data be used?
Your data will be given in a general format with all other users to the contest hosts. They will not be able to see your specific age or location.
The location is general.
Q.How do i change my password?
On the right section of the edit profile, click on the lock and enter your new password.
Q. How is the prize distributed?
The prize will be distributed by gift card at the location chosen by the application host.
Q.What currency is the prize?
Canadian Currency
Q.Are minors allowed on this site?
Yes, but they must have parental consent
`